<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MST-101-HP" name="chrome Test3" tests="1" failures="1" timestamp="31 Jan 2017 09:24:35 GMT" time="84.341" errors="0">
  <testcase name="contactCreation" time="61.858" classname="main_page.TestEngine">
    <failure type="exception.CustomException" message="The value TestAutomationis not matched with the given value Test">
      <![CDATA[exception.CustomException: The value TestAutomationis not matched with the given value Test
	at Page_Object_page.contactPage.accountNameVerify(contactPage.java:88)
	at main_page.TestEngine.contactCreation(TestEngine.java:295)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- contactCreation -->
</testsuite> <!-- chrome Test3 -->
